version: '2.1'

services:
  caddy:
    container_name: caddy
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "9090:9090"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  heplify-server:
    image: sipcapture/hepop:master
    container_name: heplify-server
    ports:
      - "8080:8080"
      - "9060:9060"
      - "9060:9060/udp"
    volumes:
      - ./conf/myconfig.js:/app/myconfig.js
    environment:
      HEPOP_HOST: 0.0.0.0
      HEPOP_PROTO: http
      HEPOP_ID: HEPOP_101
      HEPOP_PORT: 8080
      INFLUXDB_HOST: telegraf
      INFLUXDB_PORT: 8094
      INFLUXDB_DB: homer
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
     - elasticsearch

  telegraf:
    image: telegraf:1.8-alpine
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    expose:
      - 8094
    ports:
      - "8094:8094"
    depends_on:
      - heplify-server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.1
    container_name: elasticsearch
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
